# Use a imagem oficial do PHP 8.0 com Apache como base
FROM php:8.0-apache

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos do projeto para o diretório de trabalho
COPY . .

# Instale as extensões PHP necessárias
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Expõe a porta que o servidor web irá rodar
EXPOSE 8080

# Comando para iniciar o servidor web
CMD ["apache2-foreground"]